language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
    # PyPy versions
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - "pip install ."
  - "pip install nose"
script: nosetests
